### ISSUE TITLE
Capture AITemplate errors for exceptions

### ISSUE THREAD

**Issue by hlky** [hlky/AITemplate#9]
Internal AITemplate errors display above a traceback, this is easily missed when a user is reporting an issue.

Example
```
[11:53:32] model_interface.cu:306: Error: [gemm_rcr_64.cu] Got cutlass error: Error Internal at: 198
Traceback (most recent call last):
  File "H:\diffusers_ait\builder\svd.py", line 99, in <module>
    benchmark_ait.benchmark_module(module=module)
  File "h:\ait\python\aitemplate\testing\benchmark_ait.py", line 43, in benchmark_module
    mean, std, _ = module.benchmark_with_tensors(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\ait\python\aitemplate\compiler\model.py", line 729, in benchmark_with_tensors
    mean, std, ait_outputs = self.benchmark(
                             ^^^^^^^^^^^^^^^
  File "h:\ait\python\aitemplate\compiler\model.py", line 685, in benchmark
    self.DLL.AITemplateModelContainerBenchmark(
  File "h:\ait\python\aitemplate\compiler\model.py", line 196, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerBenchmark
```

Ideally we would see something like
```
RuntimeError: AITemplateModelContainerBenchmark - model_interface.cu:306: Error: [gemm_rcr_64.cu] Got cutlass error: Error Internal at: 198
```

**Comment by hlky** [comment]
Closed by [ade1a98](https://github.com/hlky/AITemplate/commit/ade1a9819295dee684237112ca8f9467738e5f2b)
